version: '3.7'

services:
  web:
    build: ./app
    #command: sh -c "python manage.py runserver 0.0.0.0:8000"
    command: ls -l
    volumes:
      - ./app/:/user/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
