# Generated by Django 3.1.2 on 2020-10-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect', models.CharField(max_length=150)),
                ('expired', models.DateField()),
                ('view_count', models.IntegerField()),
            ],
        ),
    ]
